import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "meme-system-ui/tailwind.css";
import DashboardLayout from "@/components/layouts/dashboard-layout";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={`antialiased ${inter.className}`}>
        <DashboardLayout>
          {children}
        </DashboardLayout>
      </body>
    </html>
  );
}
